defaults:
  - _self_
  - task: libero_object_random
  - algo: quest
  - override hydra/launcher: basic

hydra:
  # run:
  #   dir: ./experiments/evaluate_single_task/${task.suite_name}${task.task_id}/${now:%Y.%m.%d}/${now:%H.%M.%S}
  sweep:
    dir: ./experiments/evaluate_single_task/${task.suite_name}/mixed_datasets
    subdir: ${seed}/${hydra.job.num}

training:
  use_tqdm: true
  n_epochs: 0
  do_profile: false
  resume: false
  load_obs: false

# Rollout settings
rollout:
  enabled: true
  rollouts_per_env: 5
  num_parallel_envs: 5
  max_episode_length: ${eval:'${task.horizon} * 2'}
  n_video: 0
  fps: 24
  debug: false

# General settings
exp_name: debug
variant_name: null
seed: 6000
device: cuda:0
stage: 1 # 0 - pretrain autoencoder, 1 - train multitask, 2 - finetune multitask
output_prefix: ./experiments
data_prefix: ./data
make_unique_experiment_dir: true

# IMPORTANT: Change this to the directory where your checkpoints are stored
checkpoint_dir: /path/to/your/checkpoint/

# Evaluate all checkpoints in checkpoint_dir (if it's a folder). When false, an interactive selection is shown.
eval_all_checkpoints: false
# Optional filename glob to filter checkpoints when eval_all_checkpoints is true, e.g., "multitask_model_epoch_*.pth"
checkpoint_pattern: null
