defaults:
  - train_debug_base
  - _self_

stage: 1 # 0 - pretrain autoencoder, 1 - train multitask, 2 - finetune multitask

logging_folder: prior

training:
  n_epochs: 100 # on libero: 20 for quest and 100 for other algos, 100 on metaworld for all algos

rollout:
  interval: 20 # rollout every ${rollout.interval} epochs
  rollouts_per_env: 5
  num_parallel_envs: 5 # 5 recommended for libero, 1 for metaworld

logging:
  project: mixed_dataset